version: 2.1
orbs:
  gh: circleci/github-cli@2.0

parameters:
  sdk-version:
    type: string
    default: "4.4.0"
  changelog:
    type: string
    default: ""
  run-release-workflow:
    type: boolean
    default: false

jobs:
  release:
    parameters:
      sdk-version:
        type: string
      changelog:
        type: string
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - gh/install
      - add_ssh_keys
      - run:
          name: Download SDK zip from private repo
          command: |
            gh release download --repo $PRIVATE_SDK_REPO <<parameters.sdk-version>>
      - run:
          name: Calculate new checksum
          command: echo "CHECKSUM=$(shasum -a 256 FlowplayerSDK.zip | awk '{print $1}')" >> $BASH_ENV
      - run:
          name: Update SDK Manifests with new version
          command: ./Scripts/UpdateManifests.bash <<parameters.sdk-version>> $CHECKSUM
      - run:
          name: Commit and Push Package.swift and FlowplayerSDK.podspec
          command: |
            git config --global user.email "$SRE_EMAIL"
            git config --global user.name "CircleCI Bot"
            git add Package.swift FlowplayerSDK.podspec
            git commit -m "release: <<parameters.sdk-version>> [skip ci]"
            git push origin main
      - run:
          name: Create CHANGELOG.md
          command: |
            echo "<<parameters.changelog>>" | base64 --decode > CHANGELOG.md
      - run:
          name: Publish release
          command: gh release create <<parameters.sdk-version>> ./FlowplayerSDK.zip ./Documentation.zip -t "v<<parameters.sdk-version>>" -F ./CHANGELOG.md

workflows:
  release:
    when: <<pipeline.parameters.run-release-workflow>>
    jobs:
      - release:
          sdk-version: <<pipeline.parameters.sdk-version>>
          changelog: <<pipeline.parameters.changelog>>
