name: Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag associated with the release"
        required: true
        type: string
      changelog:
        description: "Changelog associated with the release"
        required: true
        type: string

jobs:
  publish-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download release asset from private repo
        run: |
          gh release download --pattern '*.zip' --repo ${{ secrets.PRIVATE_REPO }}
          ls -al
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Calculate new checksum
        run: |
          echo "CHECKSUM=$(shasum -a 256 FlowplayerSDK.zip | awk '{print $1}')" >> $GITHUB_ENV

      - name: Make UpdateManifests script executable
        run: chmod +x ./Scripts/UpdateManifests.bash

      - name: Update SDK Manifests
        run: ./Scripts/UpdateManifests.bash ${{ inputs.tag }} ${{ env.CHECKSUM }}

      - name: Commit and Push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Bot"
          git add Package.swift FlowplayerSDK.podspec
          git commit -m "release: v${{ inputs.tag }}"
          git push origin main

  publish-cocoapods:
    runs-on: ubuntu-latest
    needs: publish-manifest
    steps:
      - uses: actions/checkout@v4
