name: Publish

on:
  release:
    types: [released]

jobs:
  publish-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download release asset from public repo
        run: |
          gh release download --pattern 'FlowplayerSDK.zip'
        env:
          GH_TOKEN: ${{ github.token }}

      - name: DEBUG
        run: ls -al

      - name: Calculate new checksum
        run: |
          echo "CHECKSUM=$(shasum -a 256 FlowplayerSDK.zip | awk '{print $1}')" >> $GITHUB_ENV

      - name: Make UpdateManifests script executable
        run: chmod +x ./Scripts/UpdateManifests.bash

      - name: Update SDK Manifests
        run: ./Scripts/UpdateManifests.bash ${{ github.ref_name }} ${{ env.CHECKSUM }}

      - name: Commit and Push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Bot"
          git add Package.swift FlowplayerSDK.podspec
          git commit -m "release: ${{ github.ref_name }}"
          git push origin main

  publish-cocoapods:
    runs-on: ubuntu-latest
    needs: publish-manifest
    steps:
      - uses: actions/checkout@v4
