name: Release Deploy

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'New Version'
        default: '4.0.0'
        required: true

jobs:
  updatePackageSwift:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Extract Tag Name
      id: tag_name
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      if: github.event_name == 'release'
    - name: Update Package.swift with release ref
      run: ./Scripts/UpdateManifests.bash $TAG_NAME
      if: github.event_name == 'release'
    - name: Update SDK Manifests with new version
      run: ./Scripts/UpdateManifests.bash ${{ github.event.inputs.newVersion }}
      if: github.event_name == 'workflow_dispatch'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: 'release: ${{github.event.inputs.newVersion}}'
        branch: 'release/${{github.event.inputs.newVersion}}'
        base: main
