name: Release Deploy

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'New Version'
        default: '4.0.0'
        required: true
        
jobs:
  updatePackageSwift:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update Package.swift with release ref
      run: ./Scripts/UpdatePackageManifest.bash ${{ github.ref }}
      if: github.event_name == 'release'
    - name: Update Package.swift with new version
      run: ./Scripts/UpdatePackageManifest.bash ${{ github.event.inputs.newVersion }}
      if: github.event_name == 'workflow_dispatch'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        base: main
